# Generated by Django 4.2.1 on 2023-11-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='img',
            field=models.ImageField(max_length=500, null=True, upload_to='context/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
